### ISSUE TITLE
crash when run as plugin

### ISSUE THREAD

**Issue by wanxewoj** [saubyk/c-lightning-REST#22]
When I run this via `Option 1: Run as c-lightning plugin` all looks fine at first in the `.lightning/debug.log`:

```
plugin-plugin.js --- Starting the cl-rest server ---
INFO plugin-plugin.js Changing the working directory to :/opt/src/c-lightning-REST
INFO plugin-plugin.js Reading SSL cert and key
INFO plugin-plugin.js Reading rootkey for macaroon
INFO plugin-plugin.js macaroon converted to base64:
INFO plugin-plugin.js <REDACTED>Q=
INFO plugin-plugin.js --- cl-rest api server is ready and listening on port: 3001 ---
```

However the the api server is not running and I'll see:
```
$ ps aux | grep node
lightning  1393  0.0  0.0      0     0 ?        Z    10:31   0:00 [node] <defunct>
```

Which means it crashed for some reason. But there's no more info in the `.lightning/debug.log`. Is there any way to debug c-lightning plugins? Or is there a way I can write the whole STDOUT to a file when it is run as plugin?

If I run the api-server standalone it works and there's no crash.

**Comment by saubyk** [comment]
Hi @wanxewoj 
Did your `npm install` ran without any issue?

**Comment by wanxewoj** [comment]
> Hi @wanxewoj
> Did your `npm install` ran without any issue?

Yes. No issues.

And as I wrote, `Option 2: Run as an API server` runs without issues. Only when run as a plugin it crashes. I'm using `c-lightinging` master branch.

**Comment by darosior** [comment]
> I'm using c-lightinging master branch.

FWIW the master had a bug with dynamic plugin until lately.

@wanxewoj I updated [clightningjs](https://github.com/darosior/clightningjs), can you try with the latest release ? If you experience a crash again could you give me c-lightning logs ?

**Comment by saubyk** [comment]
@darosior thanks for looking into this. I meant to tag you here. :-)

**Comment by saubyk** [comment]
@wanxewoj please pull the latest cl-rest version (0.0.4) and run it along with c-lightning v0.7.3

You issue should be addressed.
